### ISSUE TITLE
Logical Assignment

### ISSUE THREAD

**Issue by laurieontech** [js-outreach/js-outreach-groups#30]
https://github.com/tc39/proposal-logical-assignment

**Comment by MayaLekova** [comment]
If you like [this explainer](https://v8.dev/features/logical-assignment), we could just tweet it? It seems brief enough.

**Comment by laurieontech** [comment]
Ya, that's a good one.

**Comment by hemanth** [comment]
Trying to assign this to me.

**Comment by hemanth** [comment]
We can [close](https://dev.to/hemanth/logical-assignment-operators-in-javascript-inh) this?

**Comment by laurieontech** [comment]
Being tweet out today! So yes :)
