### ISSUE TITLE
Numeric Seperators

### ISSUE THREAD

**Issue by bkardell** [js-outreach/js-outreach-groups#35]
Let's get this done - I'll make sure to get this content, whether that is using jory's rick video or an edit or that or something... this month.

https://github.com/tc39/proposal-numeric-separator

**Comment by ljharb** [comment]
This proposal is seeking stage 4 in 10 days; what's the goal of outreach here?

**Comment by bkardell** [comment]
Sorry @ljharb I didn't see your q... This is for educational outreach as part of  https://twitter.com/StandardsIn2Min

**Comment by ljharb** [comment]
Thanks, makes perfect sense :-)

**Comment by bkardell** [comment]
posted https://twitter.com/StandardsIn2Min/status/1303412027168260096
